config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :quick_appointments
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, except: [:new]

  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	validates :user_id, presence: true
end

app/models/quick_appointment.rb
class QuickAppointment < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
	before_save { self.email = email.downcase }
	validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, 
	format: { with: VALID_EMAIL_REGEX }
	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in to perform that action"
  		redirect_to root_path
  	end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
			flash[:success] = "Article was successfully created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article was updated"
			redirect_to article_path(@article)
		else
			flash[:danger] = "Article was not updated"
			render 'edit'
		end
	end

	def show

	end

	def destroy
		@article.destroy
		flash[:danger] = "Article was deleted"
		redirect_to articles_path
	end

	private
		def set_article
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title, :description)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end

	def about
	end

end

app/controllers/quick_appointments_controller.rb
class QuickAppointmentsController < ApplicationController
  before_action :set_quick_appointment, only: [:show, :edit, :update, :destroy]

  # GET /quick_appointments
  # GET /quick_appointments.json
  def index
    @quick_appointments = QuickAppointment.all
  end

  # GET /quick_appointments/1
  # GET /quick_appointments/1.json
  def show
  end

  # GET /quick_appointments/new
  def new
    @quick_appointment = QuickAppointment.new
  end

  # GET /quick_appointments/1/edit
  def edit
  end

  # POST /quick_appointments
  # POST /quick_appointments.json
  def create
    @quick_appointment = QuickAppointment.new(quick_appointment_params)

    respond_to do |format|
      if @quick_appointment.save
        format.html { redirect_to @quick_appointment, notice: 'Quick appointment was successfully created.' }
        format.json { render :show, status: :created, location: @quick_appointment }
      else
        format.html { render :new }
        format.json { render json: @quick_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quick_appointments/1
  # PATCH/PUT /quick_appointments/1.json
  def update
    respond_to do |format|
      if @quick_appointment.update(quick_appointment_params)
        format.html { redirect_to @quick_appointment, notice: 'Quick appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @quick_appointment }
      else
        format.html { render :edit }
        format.json { render json: @quick_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quick_appointments/1
  # DELETE /quick_appointments/1.json
  def destroy
    @quick_appointment.destroy
    respond_to do |format|
      format.html { redirect_to quick_appointments_url, notice: 'Quick appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quick_appointment
      @quick_appointment = QuickAppointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quick_appointment_params
      params.require(:quick_appointment).permit(:firstname, :lastname, :email, :phone, :time, :loan_amt)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create 
		user = User.find_by(email: params[:session][:email].downcase)
		if user  && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have logged in"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome to the alpha blog #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success] = "Your account was updated successfully"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user = User.find(params[:id])
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = { size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quick_appointments_helper.rb
module QuickAppointmentsHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well well-lg">
				<div class="article-title">
					<%= link_to article.title, article_path(article) %>
				</div>
				<div class="article-body">
					<%= truncate(article.description, length: 100) %>
					<div class="article-meta-details">
					<small>Created by: <%= article.user.username if article.user %>,
										<%= time_ago_in_words(article.created_at) %> ago,
										last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
					</div>
				</div>
				<div class="article-actions">
					<%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
					<%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :title %>
			</div>
			<div class="col-sm-8">
				<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :description %>
			</div>
			<div class="col-sm-8">
				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit class: 'btn btn-primary btn-large' %>
			</div>
		</div>

		<% end %>
		<div class="col-xs-4 col-xs-offset-2">
		[ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
		</div>	
	</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
	<h1 align="center">Listing all articles</h1>
	<div align="center">
		<%= will_paginate %>
	</div>
	<%= render 'article', obj: @articles %>
	<div align="center">
		<%= will_paginate %>
	</div>

app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<% if @article.user %>
	<ul class="listing">
		<div class="row" align="center">
			<div class="col-md-4 col-md-offset-4">
				<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
				<li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
				<li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
			</div>
		</div>
	</ul>	
	<% end %>
	<h4 class="center description"><strong>Description:</strong></h4>
	<hr>
	<%= simple_format(@article.description) %>
	<div class="article-actions">
	<%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
	<%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
	<%= link_to "Back", articles_path, class: "btn btn-xs btn-success" %>
	</div>
</div>

app/views/home/index.html.erb
  <ul class='slideshow'>
    <li>
      <span>Summer</span>
    </li>
    <li>    
      <span>Fall</span>
    </li>
    <li>    
      <span>Winter</span>
    </li>
    <li>
      <span>Spring</span>
    </li>
  </ul>
  
    <div class="parallax first-section">
        <div class="container">
            <div class="row">
                <div class="col-md-6 wow slideInLeft hidden-xs hidden-sm">
                    <div class="contact_form">
                        <h3><i class="fa fa-envelope-o grd1 global-radius"></i> QUICK APPOINTMENT</h3>
                        <form id="contactform1" class="row" name="contactform" method="post">
                            <fieldset class="row-fluid">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="first_name1" id="first_name1" class="form-control" placeholder="First Name">
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="last_name1" id="last_name1" class="form-control" placeholder="Last Name">
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <input type="email" name="email1" id="email1" class="form-control" placeholder="Your Email">
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="phone1" id="phone1" class="form-control" placeholder="Your Phone">
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <label class="sr-only">Select Time</label>
                                    <select name="select_service1" id="select_service1" class="selectpicker form-control" data-style="btn-white">
                                        <option value="selecttime">Select Time</option>
                                        <option value="Weekdays">Weekdays</option>
                                        <option value="Weekend">Weekend</option>
                                    </select>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <label class="sr-only">What is max price?</label>
                                    <select name="select_price1" id="select_price1" class="selectpicker form-control" data-style="btn-white">
                                        <option value="$100 - $2000">$100 - $2000</option>
                                        <option value="$2000 - $4000">$2000 - $4000</option>
                                        <option value="$4000 - $10000">$4000 - $10000</option>
                                    </select>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                                    <button type="submit" value="SEND" id="submit1" class="btn btn-light btn-radius btn-brd grd1 btn-block">Get an Appointment</button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
        <div class="col-md-6 col-sm-12">
                    <div class="big-tagline clearfix">
                        <h2>Sell Your Property with CITY Real Estate</h2>
                        <p class="lead">With CITY Real Estate responsive landing page template, you can promote your all property & real estate projects. </p>
                        <a data-scroll href="#gallery" class="btn btn-light btn-radius grd1 btn-brd">View Gallery</a>
                    </div>
                </div>
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

    <div id="agent" class="parallax section db parallax-off" style="background-image:url('/uploads/parallax_02.png');">
        <div class="container">
            <div class="section-title row text-center">
                <div class="col-md-8 col-md-offset-2">
                    <h3>Agent Details</h3>
                    <p class="lead">Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus. Sed a tellus quis mi rhoncus dignissim.</p>
                </div><!-- end col -->
            </div><!-- end title -->

            <div class="row">
                <div class="col-md-6">
                    <div class="message-box">
                        <h4>The Agent</h4>
                        <h2>Jenny Martines</h2>
                        <p class="lead">Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus. Sed a tellus quis mi rhoncus dignissim.</p>

                        <p> Integer rutrum ligula eu dignissim laoreet. Pellentesque venenatis nibh sed tellus faucibus bibendum. Sed fermentum est vitae rhoncus molestie. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. </p>

                        <a href="#contact" data-scroll class="btn btn-light global-radius btn-brd grd1 effect-1">Contact Me</a>
                    </div><!-- end messagebox -->
                </div><!-- end col -->
        <div class="col-md-3">
                    <div class="post-media wow fadeIn">
                        <img src="/uploads/agent.jpg" alt="" class="img-responsive">
                        <a href="http://www.youtube.com/watch?v=nrJtHemSPW4" data-rel="prettyPhoto[gal]" class="playbutton"><i class="flaticon-play-button"></i></a>
                    </div><!-- end media -->
                </div><!-- end col -->
                <div class="col-md-3">
                    <div class="agencies_meta clearfix">
                        <span><i class="fa fa-envelope "></i> <a href="mailto:support@sitename.com">support@sitename.com</a></span>
                        <span><i class="fa fa-link "></i> <a href="#">www.sitename.com</a></span>
                        <span><i class="fa fa-phone-square "></i> +1 232 444 55 66</span>
                        <span><i class="fa fa-print "></i> +1 232 444 55 66</span>
                        <span><i class="fa fa-facebook-square "></i> <a href="#">facebook.com/tagline</a></span>
                        <span><i class="fa fa-twitter-square "></i> <a href="#">twitter.com/tagline</a></span>
                        <span><i class="fa fa-linkedin-square "></i> <a href="#">linkedin.com/tagline</a></span>
                    </div><!-- end agencies_meta -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div>
    </div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
		<div class='alert alert-<%= "#{name}" %>'>
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="#" id="logo">Alpha Blog</a>-->
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/about.html.erb
<h1>About Blog</h1>

<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>

<%= link_to 'About', about_path %> |
<%= link_to 'Alpha Blog', articles_path %>

app/views/quick_appointments/_form.html.erb
<%= form_with(model: quick_appointment, local: true) do |form| %>
  <% if quick_appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quick_appointment.errors.count, "error") %> prohibited this quick_appointment from being saved:</h2>

      <ul>
      <% quick_appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :quick_appointment_firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :quick_appointment_lastname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :quick_appointment_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :quick_appointment_phone %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time, id: :quick_appointment_time %>
  </div>

  <div class="field">
    <%= form.label :loan_amt %>
    <%= form.text_field :loan_amt, id: :quick_appointment_loan_amt %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quick_appointments/edit.html.erb
<h1>Editing Quick Appointment</h1>

<%= render 'form', quick_appointment: @quick_appointment %>

<%= link_to 'Show', @quick_appointment %> |
<%= link_to 'Back', quick_appointments_path %>

app/views/quick_appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quick Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Time</th>
      <th>Loan amt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quick_appointments.each do |quick_appointment| %>
      <tr>
        <td><%= quick_appointment.firstname %></td>
        <td><%= quick_appointment.lastname %></td>
        <td><%= quick_appointment.email %></td>
        <td><%= quick_appointment.phone %></td>
        <td><%= quick_appointment.time %></td>
        <td><%= quick_appointment.loan_amt %></td>
        <td><%= link_to 'Show', quick_appointment %></td>
        <td><%= link_to 'Edit', edit_quick_appointment_path(quick_appointment) %></td>
        <td><%= link_to 'Destroy', quick_appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quick Appointment', new_quick_appointment_path %>

app/views/quick_appointments/new.html.erb
<h1>New Quick Appointment</h1>

<%= render 'form', quick_appointment: @quick_appointment %>

<%= link_to 'Back', quick_appointments_path %>

app/views/quick_appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @quick_appointment.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @quick_appointment.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @quick_appointment.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @quick_appointment.phone %>
</p>

<p>
  <strong>Time:</strong>
  <%= @quick_appointment.time %>
</p>

<p>
  <strong>Loan amt:</strong>
  <%= @quick_appointment.loan_amt %>
</p>

<%= link_to 'Edit', edit_quick_appointment_path(@quick_appointment) %> |
<%= link_to 'Back', quick_appointments_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "error") %>
						prohibited this object from being saved:
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg|%>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :username %>
			</div>
			<div class="col-sm-8">
				<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :email %>
			</div>
			<div class="col-sm-8">
				<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :password %>
			</div>
			<div class="col-sm-8">
				<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
			</div>
		</div>		
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
			</div>
		</div>

		<% end %>
		<div class="col-xs-4 col-xs-offset-2">
		[ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
		</div>	
	</div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit User Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>
<div align="center">
	<%= will_paginate %>
	<% @users.each do |user| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li><%= link_to gravatar_for(user), user_path(user) %></li>
					<li class="article-title"><%= link_to user.username, user_path(user) %></li>
					<li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
				</div>
			</div>
		</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
	<div class="col-md-4 col-md-offset-5 center">
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="center">
	<%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
	<%= will_paginate @user_articles %>
</div>